### ISSUE TITLE
propose and request credential fail without errors

### ISSUE THREAD

**Issue by AlexAndrei98** [tdiesler/nessus-didcomm#132]
While sending a propose-credential or request-credential if one does not send media_type and format of attachment then a response is not provided nor an error

**Comment by tdiesler** [comment]
My tests suggests that the mediaType property can be null
format now also defaults "https://www.w3.org/TR/vc-data-model/"

**Comment by tdiesler** [comment]
This does not (yet) include "Problem Reports" https://github.com/tdiesler/nessus-didcomm/issues/108
