### ISSUE TITLE
DIDCOMM v2 does not allow for did:key. 

### ISSUE THREAD

**Issue by AlexAndrei98** [tdiesler/nessus-didcomm#8]
DIDDoc must support service endpoints. 
The standard practice would be to use did:peer with numalgo 2 which is effectively a did:key with a service endpoint

**Comment by tdiesler** [comment]
Lovely thanks
https://identity.foundation/peer-did-method-spec/

**Comment by tdiesler** [comment]
We now have Out-of-Band Invitation , DID Exchange, Trust Ping, Encrypted/Signed/Plaintext Messages with DIDComm V2 using DID Key. For this we have in-memory DID Document and Secrets resolvers
